name: update-profile-daily

on:
  # Run automatically everyday at 00:05
  schedule:
  - cron: "5 0 * * *"
  
  # Allows to manually run the job at any time
  workflow_dispatch:
  
  # Run on every push on the main branch
  # push:
  #   branches: [ "main" ]

jobs:
  update_github_profile_readme:
    runs-on: ubuntu-latest
    name: Generate awesome wallpapers, random quotes, grid snake animation, wakatime stats
    permissions:
      contents: write
    timeout-minutes: 5
    
    steps:
    # Checkout main branch
    - name: Checkout main branch
      uses: actions/checkout@v4
      # with:
      #   sparse-checkout: assets

    # Generate awesome wallpapers, output a jpg at <assets> folder
    - name: Generate awesome wallpapers
      uses: huuquyet/generate-awesome-wallpapers@v1.2
      id: wallpaper
      env:
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}

    # Generate awesome joke, output a svg at <assets> folder
    - name: Generate awesome joke
      uses: huuquyet/generate-awesome-text@v1.1
      id: joke
      env:
        GEMINI_API_TOKEN: ${{ secrets.GEMINI_API_TOKEN }}

    # Generate random quotes from api.quotable.io
    # Print the model_id and prompt from above wallpaper step
    - name: Run random_quotes.sh to generate random quotes from api.quotable.io
      run: |
        sudo apt update
        ./random_quotes.sh

    # Generate a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <assets> folder
    # the content will be available at main branch after push step
    - name: Generate assets github-contribution-grid-snake.svg
      uses: Platane/snk/svg-only@v3
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          assets/github-contribution-grid-snake.svg
          assets/github-contribution-grid-snake-dark.svg?palette=github-dark

    # Push awesome wallpapers, random quotes & grid snake animation to main branch
    # Note: the following account information will not work on GHES
    - name: Push awesome wallpapers, random quotes and grid snake animation to main branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m ":robot: Updated awesome wallpaper, random quotes & grid snake animation"
        git push

    # Update WakaTime stats between START_SECTION:waka and END_SECTION:waka blocks in README.md
    - name: Update README.md with WakaTime stats
      uses: anmol098/waka-readme-stats@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        SHOW_SHORT_INFO: "False"
        SHOW_LINES_OF_CODE: "False"
        SHOW_TOTAL_CODE_TIME: "False"
        SHOW_PROFILE_VIEWS: "False"
        SHOW_COMMIT: "True"
        SHOW_DAYS_OF_WEEK: "True"
        SHOW_LANGUAGE: "True"
        SHOW_OS: "False"
        SHOW_PROJECTS: "False"
        SHOW_TIMEZONE: "False"
        SHOW_EDITORS: "False"
        SHOW_LANGUAGE_PER_REPO: "False"
        SHOW_LOC_CHART: "False"
        COMMIT_MESSAGE: ":robot: Updated the WakaTime stats"
