name: Generate grid snake animation, WakaTime stats and random quotes

on:
  # Run automatically everyday at 00:05
  schedule:
  - cron: "5 0 * * *"
  
  # Allows to manually run the job at any time
  workflow_dispatch:
  
  # Run on every push on the main branch
  # push:
  #   branches:
  #   - main

jobs:
  update_github_profile_readme:
    runs-on: ubuntu-latest
    name: A job to generate grid snake animation, wakatime stats and random quotes
    permissions:
      contents: write
    timeout-minutes: 5
    
    steps:
    # Checkout main branch
    - name: Checkout main branch
      uses: actions/checkout@v4
      # with:
      #   sparse-checkout: assets

    # Generate a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <assets> folder
    # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<assets>/<file>, or as github page
    - name: Generate assets github-contribution-grid-snake.svg
      uses: Platane/snk/svg-only@v3
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          assets/github-contribution-grid-snake.svg
          assets/github-contribution-grid-snake-dark.svg?palette=github-dark

    # Generate random quotes from api.quotable.io
    - name: Run random_quotes.sh to generate random quotes from api.quotable.io
      run: |
        sudo apt update
        sh ./random_quotes.sh

    # Generate awesome wallpapers, output a jpg at <assets> folder
    - name: Generate awesome wallpapers
      uses: huuquyet/generate-awesome-wallpapers@v0.1
      env:
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}

    # Push grid snake animation and random quotes to main branch
    - name: Push grid snake animation, random quotes and wallpaper to main branch
      run: |
        # Note: the following account information will not work on GHES
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m ":robot: Updated the grid snake animation and random quotes"
        git push

    # Update WakaTime stats between START_SECTION:waka and END_SECTION:waka blocks in README.md
    - name: Update README.md with WakaTime stats
      uses: anmol098/waka-readme-stats@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        SHOW_SHORT_INFO: "False"
        SHOW_LINES_OF_CODE: "False"
        SHOW_TOTAL_CODE_TIME: "False"
        SHOW_PROFILE_VIEWS: "False"
        SHOW_COMMIT: "True"
        SHOW_DAYS_OF_WEEK: "True"
        SHOW_LANGUAGE: "True"
        SHOW_OS: "False"
        SHOW_PROJECTS: "False"
        SHOW_TIMEZONE: "False"
        SHOW_EDITORS: "False"
        SHOW_LANGUAGE_PER_REPO: "False"
        SHOW_LOC_CHART: "False"
        COMMIT_MESSAGE: ":robot: Updated the WakaTime stats"
